# SITE CONFIGURATION站点配置
title: OUR GAMES # your site title您的网站标题
author: FreeRacingGame # You 作者名字
description:  FreeRacing Games is the creator of Racing In Car; a highly detailed. best-in-class Racing game for fans of Racing in car . 
baseurl:  # the subpath of your site, e.g. /blog子路径
url: "https://myfreegame.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# 搜索引擎优化插件
social:
  name: FreeRacingGame
  links:
    - https://play.google.com/store/apps/details?id=com.HighwayRacingInCar.FreeRacingGame
    - https://play.google.com/store/apps/details?id=com.FreeRacingGame.CitySpeedDriftRacingCar
    - https://play.google.com/store/apps/details?id=com.HighwayRacingInCar.FreeRacingGame
    - https://play.google.com/store/apps/developer?id=free+racing+game
    - https://play.google.com/store/apps/developer?id=free+racing+game
    - https://play.google.com/store/apps/developer?id=free+racing+game

# THEME SETTINGS主题设置
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
#口号
tagline: All for players
#主背景图像：使用/assets/img/=>路径将输出/assets/img/posts/sleek_lg.jpg
hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: wangxiaohua12580@gmail.com # email for form submission

twitter_username: FreeRacingGame # replace with your_twitter_username or comment to remove link from footer
github_username:  FreeRacingGame # replace with your_github_username or comment to remove link from footer
instagram_username: FreeRacingGame # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: myfreegame-github-io # to enable comments replace with your_disqus_shortname支持Disqus评论

  google_tag_manager: GTM-TVKK429 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
